# Generated by Django 5.1.1 on 2025-09-01 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0021_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoconference',
            name='created_by',
        ),
        migrations.AddField(
            model_name='videoconference',
            name='batch_instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.batchinstructor'),
        ),
    ]
