# Generated by Django 5.1.1 on 2025-09-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0022_remove_videoconference_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoconference',
            name='meeting_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
